export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const FETCH_ADMIN_REQUEST = "FETCH_ADMIN_REQUEST";
export const FETCH_ADMIN_SUCCESS = "FETCH_ADMIN_SUCCESS";
export const FETCH_ADMIN_FAIL = "FETCH_ADMIN_FAIL";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const REFRESH_SUCCESS = "REFRESH_SUCCESS";
export const REFRESH_FAIL = "REFRESH_FAIL";

export const ADMIN_REFRESH_SUCCESS = "ADMIN_REFRESH_SUCCESS";
export const ADMIN_REFRESH_FAIL = "ADMIN_REFRESH_FAIL";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const ALERT_ERROR = "ALERT_ERROR";

export const SET_TOAST = "SET_TOAST";
export const REMOVE_TOAST = "REMOVE_TOAST";
export const TOAST_ERROR = "TOAST_ERROR";

export const SOCKET_CONNECTION_REQUEST = "SOCKET_CONNECTION_REQUEST";
export const SOCKET_CONNECTION_SUCCESS = "SOCKET_CONNECTION_SUCCESS";
export const SOCKET_CONNECTION_FAIL = "SOCKET_CONNECTION_FAIL";

export const LOGOUT = "LOGOUT";

export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";

export const ADD_POSTS_SUCCESS = "ADD_POSTS_SUCCESS";
export const ADD_NEXT_POSTS = "ADD_NEXT_POSTS";
export const ADD_POSTS_FAIL = "ADD_POSTS_FAIL";

export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL = "FETCH_POST_FAIL";

export const ON_EDIT_POST_SUCCESS = "ON_EDIT_POST_SUCCESS";
export const ON_EDIT_POST_LIST_SUCCESS = "ON_EDIT_POST_LIST_SUCCESS";

export const ON_DELETE_POST_SUCCESS = "ON_DELETE_POST_SUCCESS";
export const ON_DELETE_POST_LIST_SUCCESS = "ON_DELETE_POST_LIST_SUCCESS";

export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAIL = "FETCH_COMMENTS_FAIL";

export const ADD_COMMENTS_SUCCESS = "ADD_COMMENTS_SUCCESS";
export const ADD_NEXT_COMMENTS = "ADD_NEXT_COMMENTS";
export const ADD_COMMENTS_FAIL = "ADD_COMMENTS_FAIL";

export const ON_EDIT_COMMENT_LIST_SUCCESS = "ON_EDIT_COMMENT_LIST_SUCCESS";

export const ON_DELETE_COMMENT_LIST_SUCCESS = "ON_DELETE_COMMENT_LIST_SUCCESS";
