export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const FETCH_ADMIN_REQUEST = "FETCH_ADMIN_REQUEST";
export const FETCH_ADMIN_SUCCESS = "FETCH_ADMIN_SUCCESS";
export const FETCH_ADMIN_FAIL = "FETCH_ADMIN_FAIL";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const REFRESH_SUCCESS = "REFRESH_SUCCESS";
export const REFRESH_FAIL = "REFRESH_FAIL";

export const ADMIN_REFRESH_SUCCESS = "ADMIN_REFRESH_SUCCESS";
export const ADMIN_REFRESH_FAIL = "ADMIN_REFRESH_FAIL";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const ALERT_ERROR = "ALERT_ERROR";

export const SOCKET_CONNECTION_REQUEST = "SOCKET_CONNECTION_REQUEST";
export const SOCKET_CONNECTION_SUCCESS = "SOCKET_CONNECTION_SUCCESS";
export const SOCKET_CONNECTION_FAIL = "SOCKET_CONNECTION_FAIL";

export const LOGOUT = "LOGOUT";

export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const FETCH_POSTS_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";

export const ADD_POSTS_SUCCESS = "ADD_POSTS_SUCCESS";
export const ADD_POSTS_FAIL = "ADD_POSTS_FAIL";
